const kebabList = [
  {
    id: "KebabPizza",
    img: "imagies/foods/kebab_pizza.jpg",
    titke: "Kebab pizza",
    price: 39.99,
    desc: `Pizza z mięsem Kebab <br> sos: ostry/łagodny <br>mięso: baranina/kurczak`,
  },
  {
    id: "Kebabbig",
    img: "imagies/foods/Kebabbig.jpg",
    titke: "Kebab olbrzym",
    price: 30.33,
    desc: `długość: 50cm <br> sos: ostry/łagodny <br> mięso: baranina/kurczak </p>`,
  },
  {
    id: "Kebab rollo",
    img: "imagies/foods/kebab_rollo.jpeg",
    titke: "Kebab rollo",
    price: 9.99,
    desc: `długość: 20 cm <br> sos: ostry/łagodny<br> mięso: baranina/kurczak <br>`,
  },
  {
    id: "Kebab on the plate",
    img: "imagies/foods/kebab_on_the plate.png",
    titke: "Kebab na talerzu",
    price: 19.99,
    desc: `duża ilość warzyw <br> sos: ostry/łagodny <br> mięso: baranina/kurczak`,
  },
  {
    id: "Kebab in roll",
    img: "imagies/foods/kebab_butter.jpg",
    titke: "Kebab w bułce",
    price: 19.99,
    desc: `pieczywo: jasne/ciemne <br> sos: ostry/łagodny <br> mięso: baranina/kurczak`,
  },
  {
    id: "kebab burger",
    img: "imagies/foods/kebab_burger.jpg",
    titke: "kebab burger",
    price: 25.5,
    desc: `pieczywo: jasne/ciemne <br> sos: ostry/łagodny <br> mięso: baranina/kurczak`,
  },
  {
    id: "box 1",
    img: "imagies/foods/box_1.jpg",
    titke: "Kebab box duży",
    price: 15.7,
    desc: `sos: czosnkowy/miodowy <br> sos w pojemniczku <br> mięso: baranina/kurczak`,
  },
  {
    id: "box 2",
    img: "imagies/foods/box_2.jpg",
    titke: "Kebab box mały",
    price: 9.99,
    desc: `sos: czosnkowy/miodowy <br> sos w pojemniczku <br> mięso: baranina/kurczak`,
  },
  {
    id: "chips",
    img: "imagies/foods/chips.png",
    titke: "Frytki",
    price: 7.99,
    desc: `własnej roboty <br> podane z cebulką <br> sos: keczup/majonez`,
  },
];
let card = JSON.parse(localStorage.getItem("data")) || [];
// dokonczyc kebaby powyższe,
